Repro
QubesOS/qubes-vmm-xen pull request #91
Opened 2020-10-26 08:11 UTC by fepitre

2020-10-29 21:10 UTC, marmarek requested changes

2020-10-29 21:10 UTC, marmarek commented on xen.spec.in
> +patch-0002-common-remove-gzip-timestamp.patch
Missing `Patch...:` prefix.

2020-10-29 21:37 UTC, fepitre commented on xen.spec.in
> +patch-0002-common-remove-gzip-timestamp.patch
Yes thank you.

2020-11-09 22:02 UTC, fepitre commented on debian-vm/debian/rules
> +export DEB_BUILD_MAINT_OPTIONS = hardening=+all reproducible=+fixfilepath
@marmarek: ideally, I would like to find a general way also for other distro.

2020-11-09 22:03 UTC, fepitre commented on patch-Disable-build-id.patch
> ++note_file_option ?=
The above looks brutal but now I have a reproducible build so I can tune if needed.

2020-11-13 03:14 UTC, marmarek approved these changes

2020-11-13 03:14 UTC, marmarek commented on patch-Disable-build-id.patch
> +Subject: [PATCH] Disable build-id
This is probably not acceptable upstream, as build-id is necessary for livepatching to work. But since we don't use livepatching, it's fine here.

2020-11-13 03:14 UTC, marmarek commented on patch-Strip-build-path-directories-in-tools-xen-and-xen-ar.patch
> ++CFLAGS += -ffile-prefix-map=$(XEN_ROOT)=.
This normally is set from packaging scripts, so I guess it's also unsuitable upstream. But again, here it is fine.

2020-11-13 03:15 UTC, merged